### PR TITLE
polish holidays & translation 

### PR DESCRIPTION
**Pull request by mpdx**

### CODE REVIEW

**Comment by stelgenhof** [comment]
Thank you @mpdx ! Let me review the PR. Nice to have Poland added as well :)

**Comment by stelgenhof** [comment]
There is a basic test file missing for the country/region itself. It should be called PolandTest.php and needs to contain tests which holidays you are expecting from the provider class. Check the other countries for an example.

**Comment by mpdx** [comment]
@stelgenhof aye, mate! thanks for the info!

**Comment by stelgenhof** [comment]
It seems there is no unit test for Corpus Christi. Can you add that one too?

**Pull request merged**
