### PR TITLE
Holiday provider for India

### PR DESCRIPTION
**Pull request by c960657**
New holiday provider with support for the [3 public holidays in India](https://en.wikipedia.org/wiki/Public_holidays_in_India).

I was not able to figure out when these days were made official holidays, but at least they are limited by the year of the event they are commemorating.

### CODE REVIEW

**Comment by stelgenhof** [comment]
Nice! This only include the national holidays. Have you thought about the other, various religious holidays in India?

**Comment by c960657** [comment]
I did think about it, and it is 100% relevant. But I'm afraid I don't have the time or need (or knowledge) to implement these.

There is a boatload of holidays for each of the large religions in India, so it is a considerable task. For my own purpose, I only need the official holidays, so I'll leave it there. Other developers are welcome to pick up this task and extend the provider.

If you don't want to merge this provider with only the official holidays, I totally understand.

**Comment by stelgenhof** [comment]
Thanks! Totally understand about the volume. However usually my criterium for adding a new country is when all (or nearly all) official / recognized holidays are included. This to give end-users a complete package, rather then a half implemented one :)

Let me have a think about it. 

Thanks for the work anyway as always! Sacha

**Comment by Milamber33** [comment]
Australia was far from complete before I fleshed it out...

**Comment by stelgenhof** [comment]
@Milamber33 Exceptions can be made ;)

Anyways... although Australia wasn't immediately complete indeed, it was when it became part of a release.

**Pull request closed without merging**
