### PR TITLE
Added Georgia Provider.

### PR DESCRIPTION
**Pull request by zsardarov**

### CODE REVIEW

**Comment by stelgenhof** [comment]
@zsardarov Thank you so much for this! I will review your PR in the next few days.

Cheers! Sacha

**Comment by zsardarov** [comment]
@stelgenhof I am planning to rename particular (addBaptismOfLordJesusDay) method and will re-push PR. If you have any other suggestion I will take them into account before the next PR.

**Comment by stelgenhof** [comment]
@zsardarov Sure! If you can update this PR that would be great.

**Review by stelgenhof — APPROVED** [review]
Looking good!

**Pull request merged**
