### PR TITLE
Japanese Health And Sports Day rename to Sports Day since 2020.

### PR DESCRIPTION
**Pull request by cookie-maker**
Japanese [Health And Sports Day(体育の日)]  rename to [Sports Day(スポーツの日)] since 2020.

https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html

### CODE REVIEW

**Comment by stelgenhof** [comment]
@cookie-maker Just wanted to check if you were able to review my comments.

**Comment by cookie-maker** [comment]
sorry I'm late.
Thanks, but I could not find your review comment.
Could you tell me where you commented on?

**Comment by stelgenhof** [comment]
You can find my comments here on Github in this PR.

**Comment by cookie-maker** [comment]
I am sorry I do not know how to use Github.
I still do not know the location of the comment.
Conversation Tab? Files Changed Tab?
Can I have a picture of the place where the comment is written?

**Comment by stelgenhof** [comment]
No problem. My apologies, as I don't always realize not everybody uses Github often.

On this page you can scroll down the page to see the changes and also comments and feedback from others. See this screenshot:

pr_screenshot

You can there respond or provide other comments.

Hopefully that clarifies it.

Cheers! Sacha

**Comment by cookie-maker** [comment]
Thank you for your kindness.
I understood the problem of the code by image file.
However, I can not find your review comment from above Github.

This is the screen that I see.
japanese health and sports day rename to sports day since 2020 by cookie-maker pull request 129 azuyalabsyasumi

default

Maybe, the submit review button is not pressed.

**Comment by stelgenhof** [comment]
@cookie-maker Thanks for the screenshot. Nothings is wrong. You are absolutely right, I forgot to press Submit. I feel so stupid, haha. 

I did it now, so hopefully you can see it.

Cheers! Sacha

**Comment by cookie-maker** [comment]
ありがとうございます！

I found your comment!
Thank you for review.
I Fixed the wrong point just now.

よろしくおねがいいたします！

**Comment by stelgenhof** [comment]
いつもありがとうございます！すぐにあなたの他のPRを検証します。

**Pull request merged**
