### PR TITLE
Add new day of liberation in 2025 in Berlin

### PR DESCRIPTION
**Pull request by Pyrexx**
Second try: I made a new branch, managed to execute the fixer...

This adds the new liberation day of 2025 in Berlin.

### CODE REVIEW

**Review by stelgenhof — COMMENTED** [review]
@Pyrexx The checks are good now. Thanks! I've done some updates to the develop branch so there are conflicts in your branch. If you can rebase your branch, then we should be good to merge your PR.

**Comment by Pyrexx** [comment]
@stelgenhof I don't know whats going on here. I synced my fork, did a merge, pushed to my branch, and now this pull request is closed?

**Comment by Pyrexx** [comment]
@stelgenhof I did nothing within github... I just pushed to my branch (bisides my error not rebasing but merging develop. (that is not a common workflow on our side)) I'm trying that rebasing now, but it seams a mess.

But I think I give up here.

If you want to use that code, feel free to grab it.

**Comment by stelgenhof** [comment]
@Pyrexx Could be that the merge caused the issues you've encountered. Anyway, I've include your code changes in a separate commit (see: 15701794777e4b3b83a194844fef7f27286d79e3)

**Pull request closed without merging**
