### PR TITLE
Added AbstractProvider::getHolidaysOfType

### PR DESCRIPTION
**Pull request by gisostallenberg**
this makes it possible to get only Holidays of a certain type. This makes it possible to get 'national holidays' as mentioned in the Composer description

### CODE REVIEW

**Comment by stelgenhof** [comment]
Thank you for this! This is certainly something missing now in Yasumi. However, I was thinking making something similar to what PEAR Date_Holidays is using: Filters. That seems to be a very flexible solution.

**Comment by stelgenhof** [comment]
I just released v1.0.0 of Yasumi, which includes filters. This allows you to filter holidays to only get 'national' holidays as you requested. :)

**Comment by gisostallenberg** [comment]
Thanks for adding this. Nice feature.

**Comment by stelgenhof** [comment]
Glad you like it! If you have any more wishes, ideas please create an issue :). What other countries would you like to see added first?

**Pull request closed without merging**
