### PR TITLE
Adding missing countries.

### PR DESCRIPTION
**Pull request by miguelanruiz**
Hey there,

Now is missing Colombia, Peru and Mexico, so i think you could include with this pullr, main idea is another applications can has updated dates.

Best regards,

### CODE REVIEW

**Comment by stelgenhof** [comment]
@miguelanruiz Thank you so much! This is great. I will review your PR.

**Comment by stelgenhof** [comment]
@miguelanruiz Your PR has a few issues: please check the coding style and the static analysis results. You should be able to run these checks locally and make fixes accordingly.

**Comment by miguelanruiz** [comment]
Hey there,

Its okay, i will check sr

**Comment by miguelanruiz** [comment]
I think is ready now

**Comment by stelgenhof** [comment]
Thanks! The tests will likely fail as there are some other issues. These are not related to your PR so you can ignore those. Only check any errors that are coming from your code :)

**Comment by stelgenhof** [comment]
@miguelanruiz The code styling and static analysis jobs are all fine now, however many of your unit tests are failing. You may want to check if your tests cover the calculation rules of those holidays correctly. 
(Again, please ignore any test errors from other countries).

**Comment by miguelanruiz** [comment]
Hi @stelgenhof 

Im confused with this:
image

It comes from an interface? could you help me with an example

**Comment by stelgenhof** [comment]
@miguelanruiz Just wanted to follow up after my last reply. Do you still need any help with your PR?

**Comment by stelgenhof** [comment]
@miguelanruiz Any updates? You may want to rebase your PR/branch as I fixed a few bugs.

**Pull request closed without merging**
