### PR TITLE
Adding Australia\Victoria region

### PR DESCRIPTION
**Pull request by brucealdridge**

### CODE REVIEW

**Comment by brucealdridge** [comment]
Will add support for QLD/NSW/SA and maybe more later

**Comment by stelgenhof** [comment]
Hi @brucealdridge, would you mind creating a PR for all Australia rather than bit by bit? That way I can put it in a release in it's entirety :)

**Comment by splitice** [comment]
The national ones are contained in this PR, and thats exactly what I needed.

Thanks @brucealdridge

**Comment by brucealdridge** [comment]
@stelgenhof national public holidays for Australia are in there, just not all states. 
Australia is weird - and some states have holidays on different dates (Queens Birthday, Labour Day) 

This PR at the moment contains the National holidays and all holidays for VIC. I'll get around to the other states but probably 2weeks away.

**Comment by stelgenhof** [comment]
@brucealdridge Thanks for the update. I'll merge then merge this PR as soon as possible :)
Thanks for the contribution!

**Pull request merged**
