### PR TITLE
doing my part to remove any legacy of columbus

### PR DESCRIPTION
**Pull request by Jameron**
Indigenous Peoples' Day is finally recognized as a federal holiday in the USA.

### CODE REVIEW

**Comment by alexparise** [comment]
This is an excellent and important change and I am fully in support of this change.

**Review by jlauters — APPROVED** [review]
Nice work!

**Review by alexparise — APPROVED** [review]
Good and important work.

**Comment by stelgenhof** [comment]
@Jameron Thank you very much for your PR! Looking at the Wikipedia references, it seems that Indigenous Peoples' Day and Columbus Day are still both observed albeit in different states. Shouldn't Indigenous Peoples' Day than not be added as a holiday rather than replacing Columbus Day?

**Comment by Jameron** [comment]
> @Jameron Thank you very much for your PR! Looking at the Wikipedia references, it seems that Indigenous Peoples' Day and Columbus Day are still both observed albeit in different states. Shouldn't Indigenous Peoples' Day than not be added as a holiday rather than replacing Columbus Day?

**Pull request closed without merging**
